services:
  fastapi-dev:
    build:
      context: .
      args:
        - ENV=development
    container_name: fastapi_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  fastapi-prod:
    build:
      context: .
      args:
        - ENV=production
    container_name: fastapi_prod
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
